# Generated by Django 5.1.1 on 2024-10-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('Coloración', 'Coloración'), ('Tratamientos', 'Tratamientos'), ('Línea Rubias', 'Línea Rubias'), ('Shampoo & Acondicionadores', 'Shampoo & Acondicionadores'), ('Styling & Aftercare', 'Styling & Aftercare'), ('Herramientas', 'Herramientas'), ('Manicure y Pedicure', 'Manicure y Pedicure'), ('Masajes', 'Masajes'), ('Maquillaje para eventos', 'Maquillaje para eventos'), ('Depilación', 'Depilación'), ('Tratamientos Faciales', 'Tratamientos Faciales'), ('Colorimetría', 'Colorimetría')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/items/'),
        ),
    ]
