# Generated by Django 5.1.1 on 2024-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Coloración', 'Coloración'), ('Tratamientos', 'Tratamientos'), ('Línea Rubias', 'Línea Rubias'), ('Shampoo & Acondicionadores', 'Shampoo & Acondicionadores'), ('Styling & Aftercare', 'Styling & Aftercare'), ('Herramientas', 'Herramientas'), ('Manicure y Pedicure', 'Manicure y Pedicure'), ('Masajes', 'Masajes'), ('Maquillaje para eventos', 'Maquillaje para eventos'), ('Depilación', 'Depilación'), ('Tratamientos Faciales', 'Tratamientos Faciales'), ('Colorimetría', 'Colorimetría')], max_length=255, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/items/')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=10)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['tipo'],
            },
        ),
    ]
