# Generated by Django 4.2.1 on 2024-10-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['tipo'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
