# Generated by Django 4.2.1 on 2024-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='costo2',
            field=models.IntegerField(default=0),
        ),
    ]
