# Generated by Django 5.1.1 on 2024-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_item_costo_alter_item_costo2"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("motivo", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
