# Generated by Django 5.1.1 on 2024-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="contacto",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
