# Generated by Django 4.2.1 on 2024-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=60, null=True),
        ),
    ]
