# Generated by Django 5.1.1 on 2024-10-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_reserva_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="contacto",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
