# Generated by Django 5.1.1 on 2024-12-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bloqueohorario_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloqueohorario",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueos",
                to="core.categoria",
            ),
            preserve_default=False,
        ),
    ]
