# Generated by Django 5.1.1 on 2024-10-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_categoria_reserva_categoria_servicio_servicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="categoria_servicio",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="servicio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.servicio",
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios",
                to="core.categoriaservicio",
            ),
        ),
    ]
