# Generated by Django 4.2.1 on 2024-10-29 23:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_categoriaservicio_reserva_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('Coloración', 'Coloración'), ('Tratamientos', 'Tratamientos'), ('Línea Rubias', 'Línea Rubias'), ('Shampoo & Acondicionadores', 'Shampoo & Acondicionadores'), ('Styling & Aftercare', 'Styling & Aftercare'), ('Herramientas', 'Herramientas'), ('Manicure y Pedicure', 'Manicure y Pedicure'), ('Masajes', 'Masajes'), ('Maquillaje para eventos', 'Maquillaje para eventos'), ('Depilación', 'Depilación'), ('Tratamientos Faciales', 'Tratamientos Faciales'), ('Colorimetría', 'Colorimetría')], max_length=255, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('picture', models.ImageField(null=True, upload_to='media/items/')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['tipo'],
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='item',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='iditem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipo',
        ),
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.producto'),
            preserve_default=False,
        ),
    ]
