# Generated by Django 4.2.1 on 2024-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo2',
            field=models.IntegerField(default=0),
        ),
    ]
