# Generated by Django 4.2.1 on 2024-11-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_costo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='costo',
            new_name='costo2',
        ),
    ]
