# Generated by Django 4.2.1 on 2024-11-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_costo_item_costo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='costo2',
            new_name='costo',
        ),
    ]
