# Generated by Django 4.2.1 on 2024-11-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_costo2_item_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='codigo',
        ),
    ]
