# Generated by Django 4.2.1 on 2024-11-14 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_item_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaEliminada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.reserva"
                    ),
                ),
            ],
        ),
    ]
